# permissions to do viewer floatingipsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floatingipset-viewer-role
rules:
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipsets/status
  verbs:
  - get
