# permissions to do edit floatingipsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: floatingipset-editor-role
rules:
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipsets/status
  verbs:
  - get
  - patch
  - update
