
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipassociates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipassociates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.repl.info.repl.info
  resources:
  - floatingipsets/status
  verbs:
  - get
  - patch
  - update
