apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  name: system
---
apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: controller-manager-service
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /manager
        image: rtakaishi/openstack-fip-controller:latest
        imagePullPolicy: Always
        name: manager
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SECRET_NAME
            value: $(WEBHOOK_SECRET_NAME)
          - name: OS_AUTH_URL
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_auth_url
          - name: OS_USERNAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_username
          - name: OS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_password
          - name: OS_PROJECT_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_project_name
          - name: OS_TENANT_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_tenant_name
          - name: OS_REGION_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_region_name
          - name: OS_REGION_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_region_name
          - name: OS_DOMAIN_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_domain_name
          - name: OS_IDENTITY_API_VERSION
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_identity_api_version
          - name: OS_PROJECT_DOMAIN_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_project_domain_name
          - name: OS_USER_DOMAIN_NAME
            valueFrom:
              secretKeyRef:
                name: openstack-fip-controller
                key: os_user_domain_name
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 9876
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/cert
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: webhook-server-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-secret
  namespace: system
