
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: floatingipsets.openstack.repl.info.repl.info
spec:
  group: openstack.repl.info.repl.info
  names:
    kind: FloatingIPSet
    plural: floatingipsets
  scope: ""
  validation:
    openAPIV3Schema:
      description: FloatingIPSet is the Schema for the floatingipsets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: FloatingIPSetSpec defines the desired state of FloatingIPSet
          properties:
            network:
              type: string
            nodeSelector:
              additionalProperties:
                type: string
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "make" to regenerate code after modifying this file'
              type: object
          required:
          - network
          - nodeSelector
          type: object
        status:
          description: FloatingIPSetStatus defines the observed state of FloatingIPSet
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
